

#ifndef SAYILARLISTESI_HPP
#define SAYILARLISTESI_HPP
#include "Dugum.hpp"
#include <iomanip>

class SayilarListesi{
	public:
	Dugum*dugumHead;
	Dugum*sonEklenenDugum;
	SayilarListesi();//HEAD DEGERINE NULL ATADIM BASKA BIR ISLEM YOK
	void tersCevirSayilarListesi();//DUGUM DUGUM DOLASIP SAYI SINIFINDAKI tersCevir() METODUNA ERISTIM BU SAYEDE TUM SAYILARI TERS CEVRILDI
	void dugumEkle(int sayi);//MAINDEN BU METODA ULASIP TXT DOSYASINDAKI HER SAYI ICIN DUGUM OLUSTURDUM
	void enBuyukSil();//KENDI KURDUGUM ALGORITMA ILE 	EN BUYUK SAYIYI BULDUM VE O DUGUMDEN ONCEKI VE SONRAKI DUGUMLERI BIRBIRINE BAGLAYIP BULDUGUM DUGUMU SILDIM
	void sayilarListesiYazdir();//YAZDIRMA ISLEMINI YAPTIM
	void tekSayi();//TUM DUGUMLERDE DOLASIP SAYI SINIFI ICINDEKI tekSayiBasaAl() METODUNA ERISTIM
	~SayilarListesi();//TUM DUGUMLERI DOLASIP SILDIM
};
#endif